python train.py \
--nThreads 4 \
--batchSize 2 \
--use_sau \
--lambda_feat 8.0 \
--lambda_vgg 3.0 \
--lambda_l1 2.0 \
--lambda_class 5.0 \
--lambda_tv 4.0 \
--niter 50 \
--niter_decay 70 \
--continue_train \
--which_epoch latest
